# Useful Numpy functions you should know

![](https://i.imgur.com/e8VRPiM.png)

Numpy is an open-source library for working efficiently with arrays, the name stands for Numerical Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python. It contains various features and functions, in this article we are going to see some useful function listed below.

1. ```numpy.where()```
2. ```numpy.linalg.solve()```
3. ```numpy.cumsum()```
4. ```numpy.rot90()```
5. ```numpy.tile()```

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='zerotoanalyst-numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "vinodvidhole/zerotoanalyst-numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/vinodvidhole/zerotoanalyst-numpy-array-operations


'https://jovian.ai/vinodvidhole/zerotoanalyst-numpy-array-operations'

Let's begin by installing & importing Numpy

In [2]:
!pip install numpy -q
import numpy as np

## 1. [numpy.where()](https://numpy.org/doc/stable/reference/generated/numpy.where.html#numpy.where)

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

**Syntax:**
```
numpy.where(condition[, x, y])
Return elements, either from x or y, depending on condition.
If only condition is given, return condition.nonzero().
```

### Using numpy.where() with single condition

In [5]:
# Create a Numpy array from a list
arr1 = np.array([[1, 6, 3], [4, 2, 9]])
print ('Get elements <4 from following Numpy array:')
print(arr1)
  
print("\nElements which are <4")
print(arr1[np.where(arr1<4)])

Get elements <4 from following Numpy array:
[[1 6 3]
 [4 2 9]]

Elements which are <4
[1 3 2]


In above example we are printing only elements <4 and ignore others.

### Using numpy.where() with multiple conditions

If each conditional expression is enclosed in () and & or | is used, multiple conditions are applied.

In [6]:
# Create a 3x3 matrix 
a = np.arange(9).reshape((3, 3))
print(a)

print("\nUsing multiple conditions\n")
print(np.where((a > 2) & (a < 6), 1, -1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]

Using multiple conditions

[[-1 -1 -1]
 [ 1  1  1]
 [-1 -1 -1]]


In above example, we are returning 1 if `(a > 2) & (a < 6)` condition is passed and -1 if its failed.   

### Using np.where() without any condition expression

In the previous examples we passed a condition expression as the first argument, which will be evaluated to a bool array. But we can pass a bool array too instead of that.

In [7]:
result = np.where([True, False, False],
                  ['apple', 'orange', 'banana'],
                  ['pizza', 'burger', 'fries'])
print(result)

['apple' 'burger' 'fries']


IN this example it returns an array of elements from first list where the condition is True, and elements from a second list elsewhere.

Hopefully you have learned the different usage of `numpy.where()`. Lets move ahead with the next Numpy function.

## 2. [numpy.linalg.solve()](https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html)

Solve a linear matrix equation, or system of linear scalar equations.

**Syntax:**
```
linalg.solve(a, b)
Computes the “exact” solution, x, of the well-determined, i.e., full rank, linear matrix equation ax = b.
```

### Basic example of solve()
Lets Try to solve following linear equation using built in Numpy function. 
```
4x  + 3y = 20
-5x + 9y = 26
```

In [8]:
A = np.array([[4, 3], [-5, 9]])
B = np.array([20,26])
X2 = np.linalg.solve(A,B)

print(X2)

[2. 4.]


Here we have created 2 matrices A & B, Matrix A represents x & y values and Matrix B is storing right hand side values of the equations. `np.linalg.solve()` function is returning solution of the equation.

### Real world use case for solve()

Suppose, a fruit-seller sold 20 apples and 10 oranges in one day for a total of 35. The next day he sold 17 apples and 22 oranges for 50. If the prices of the fruits remained unchanged on both the days, what was the price of one apple and one orange?

Let's say the price of one apple is x and the price of one orange is y. The above problem can be converted like this:

```
20x + 10y = 35
17x + 22y = 50
```

In [9]:
A = np.array([[20, 10], [17, 22]])
B = np.array([35, 50])
X = np.linalg.solve(A,B)

print(X)

[1.  1.5]


The output shows that the price of one apple is 1 and the price of one orange is 1.5

### Possible breaking case 

Lets discuss about the failures may occur while using this function. 

Here I am using same example of apple & oranges. Please note i did slight change in matrix A

In [10]:
A = np.array([[20], [17]])
B = np.array([35, 50])
X = np.linalg.solve(A,B)

print(X)

LinAlgError: Last 2 dimensions of the array must be square

Please checkout the error message 
```
LinAlgError: Last 2 dimensions of the array must be square
```
To use solve() function A must be square and of full-rank, i.e., all rows (or, equivalently, columns) must be linearly independent. If A matrix is not square, it means that you either have more variables than your equations or the other way around. So please try to avoid such issues while using this function.

## 3. [numpy.cumsum()](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html?highlight=cumsum#numpy.cumsum)

This function returns the cumulative sun of array elements.

**Syntax:**
```
numpy.cumsum(a, axis=None, dtype=None, out=None)[source]
Return the cumulative sum of the elements along a given axis. If axis is provided, an array is returned with the cumulative sun of elements along the axes 
```

### Cumulative Sum of Numpy Array Elements without axis

In [11]:
arr2 = np.array(
    [[1, 2],
     [3, 4],
     [5, 6]])
print(arr2)
total = np.cumsum(arr2)
print('\nCumulative Sum of all the elements is', total)

[[1 2]
 [3 4]
 [5 6]]

Cumulative Sum of all the elements is [ 1  3  6 10 15 21]


Here, the matrix is first flattened to array [ 1 2 3 4 5 6]. Then the cumulative sum is calculated, resulting in [ 1 3 6 10 15 21] (i.e. [1, (1+2), (1+2+3) ....]) 

### Cumulative Sum along the axis

In [12]:
arr3 = np.array(
    [[25, 88],
     [11, 4],
     [-8, 9]])
print(arr3)

axis_0_total = np.cumsum(arr3, axis=0)
print('\nCumulative Sum of elements at 0 axis :\n',axis_0_total)

axis_1_total = np.cumsum(arr3, axis=1)
print('\nCumulative Sum of elements at 1 axis :\n',axis_1_total)

[[25 88]
 [11  4]
 [-8  9]]

Cumulative Sum of elements at 0 axis :
 [[ 25  88]
 [ 36  92]
 [ 28 101]]

Cumulative Sum of elements at 1 axis :
 [[ 25 113]
 [ 11  15]
 [ -8   1]]


you can see below how the calculation is performed for each case.
Explanation for 0 axis:
```
[[ 25         88    ]
 [ 25+11      88+4  ]
 [ 25+11+(-8) 88+4+9]]
```

Explanation for 1 axis:
```
[[ 25  25 +88]
 [ 11  11+4  ]
 [ -8  -8+9  ]]
```


### Specifying data type for the cumulative sum array

In [13]:
arr4 = np.array(
    [[1, 2],
     [3, 4.6],
     [5, 6]])

print(arr4)
total_1_axis = np.cumsum(arr4, axis=1, dtype=int)
print('\nCumulative Sum of elements at 1-axis is:\n',total_1_axis)

[[1.  2. ]
 [3.  4.6]
 [5.  6. ]]

Cumulative Sum of elements at 1-axis is:
 [[ 1  3]
 [ 3  7]
 [ 5 11]]


in this example output is converted to int data type.

This concludes the `np.cumsum()` function. 

## 4. [numpy.rot90()](https://numpy.org/doc/stable/reference/generated/numpy.rot90.html?)

This function rotates an array by 90 degrees in the plane specified by axes.

**Syntax**
```
numpy.rot90(m, k=1, axes=(0, 1))

Rotate an array by 90 degrees in the plane specified by axes.
Rotation direction is from the first towards the second axis.
```

### Basic example of Numpy rot90() function

In [15]:
arr = np.array([[1,2],[3,4]], int)
print('Input Array :\n',arr)

print('Output Array:\n',np.rot90(arr))

Input Array :
 [[1 2]
 [3 4]]
Output Array:
 [[2 4]
 [1 3]]


In above example input array is rotated anti-clockwise by 90 degree.

## Using Numpy rot90() function with argument.

In [16]:
arr2 = np.arange(9).reshape(3,3)
print('Input Array :\n',arr2)

print('Output Array:\n',np.rot90(arr2,-1))

Input Array :
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Output Array:
 [[6 3 0]
 [7 4 1]
 [8 5 2]]


In above example In above example input array is rotated clockwise by 90 degree.

### Real world use case of rot90()

Create a 8x8 matrix and fill it with a checkerboard pattern?

In [3]:
my_arr = np.rot90(np.identity(2, dtype = int))

my_arr2 = np.vstack((my_arr,my_arr,my_arr,my_arr))
np.hstack((my_arr2,my_arr2,my_arr2,my_arr2))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

This is 3 step solution, first we are creating 2x2 identity matrix and then rotating the matrix by 90 degree. Next step is use `vstack` & `hstack` functions to get required output. 

Note : this may not be the perfect solution, I am using these function just for the sake of this tutorial.

Now lets move ahead with the last function.

## 5. [numpy.tile()](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

This function creates a new array by repeating an input array.

**Syntax**
```
numpy.tile(A, reps)

A: The input array.
reps: The number of repetitions of A along each axis.
```

### Basic example of Numpy tile function

In [20]:
arr = np.array([0, 1, 2])

print('Input array :', arr)
c = np.tile(arr, 2)

print('\n Output :', c)

Input array : [0 1 2]

 Output : [0 1 2 0 1 2]


In this example we are trying to repeat the `arr` twice using `tile` function 

### Using tile to repeat array vertically 

In [21]:
arr = np.array([11, 22, 33])
print('Input array :', arr)

reps = (3,1)
c = np.tile(arr, reps)
print('\n Output :\n', c)

Input array : [11 22 33]

 Output :
 [[11 22 33]
 [11 22 33]
 [11 22 33]]


Since reps has value (3, 1) tile function is repeating array three times vertically. you can further expand this repetition horizontally just by increasing second element of `reps` 

### Real world use case of tile()

I am using same checkerboard problem but lets improve the earlier solution using tile function.

Create a 8x8 matrix and fill it with a checkerboard pattern?

Lets use above information to solve this question.

In [22]:
my_arr = np.rot90(np.identity(2, dtype = int))

reps = (4,4)
print('Printing 8x8 checkerboard pattern')
np.tile(my_arr, reps)

Printing 8x8 checkerboard pattern


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

We first created 2x2 identity matrix and rotate that matrix by 90 degree , and then used `tile` function to repeat this matrix horizontally and vertically 4 times each.


## Reference Links

References to some useful links.
* https://numpy.org/doc/stable/user/quickstart.html
* https://numpy.org/doc/stable/reference/index.html


## Conclusion

In this article, we learned following Numpy functions.

* `numpy.where()`
* `numpy.linalg.solve()`
* `numpy.cumsum()`
* `numpy.rot90()`
* `numpy.tile()`

I hope I was able to teach you these functions , and it would useful in you data science journey.

Thank you for reading. Happy coding!!!



In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>